project_id = "ilgweiztccnsmktspwzd"
verify_jwt = false

[functions.get-youtube-audio]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false